package test.model;

import java.io.Serializable;
import java.util.Date;

public class Student implements Serializable {

    private Long uuid;

    private Date createTime;

    private Date updateTime;

    private String address;

    private Date birthDate;

    private String sex;

    private String studentName;

    private String studentNum;

    private Long aliasClassId;

    private String isDelete;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.uuid
     *
     * @return the value of STUDENT.uuid
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public Long getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.uuid
     *
     * @param uuid the value for STUDENT.uuid
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public void setUuid(Long uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.create_time
     *
     * @return the value of STUDENT.create_time
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.create_time
     *
     * @param createTime the value for STUDENT.create_time
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.update_time
     *
     * @return the value of STUDENT.update_time
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.update_time
     *
     * @param updateTime the value for STUDENT.update_time
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.address
     *
     * @return the value of STUDENT.address
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.address
     *
     * @param address the value for STUDENT.address
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.birth_date
     *
     * @return the value of STUDENT.birth_date
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.birth_date
     *
     * @param birthDate the value for STUDENT.birth_date
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.sex
     *
     * @return the value of STUDENT.sex
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.sex
     *
     * @param sex the value for STUDENT.sex
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.student_name
     *
     * @return the value of STUDENT.student_name
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.student_name
     *
     * @param studentName the value for STUDENT.student_name
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.student_num
     *
     * @return the value of STUDENT.student_num
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.student_num
     *
     * @param studentNum the value for STUDENT.student_num
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.alias_class_id
     *
     * @return the value of STUDENT.alias_class_id
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public Long getAliasClassId() {
        return aliasClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.alias_class_id
     *
     * @param aliasClassId the value for STUDENT.alias_class_id
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public void setAliasClassId(Long aliasClassId) {
        this.aliasClassId = aliasClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.is_delete
     *
     * @return the value of STUDENT.is_delete
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.is_delete
     *
     * @param isDelete the value for STUDENT.is_delete
     * @mbg.generated Sat Aug 29 17:53:19 CST 2020
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}